// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB3P08uyjw8_s_sXi6Gvz7z9t8ITee2MM',
    appId: '1:276682577009:web:0f2dcb08974ef2836237d0',
    messagingSenderId: '276682577009',
    projectId: 'feca-82a65',
    authDomain: 'feca-82a65.firebaseapp.com',
    storageBucket: 'feca-82a65.appspot.com',
    measurementId: 'G-E7M6ZDKSYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNZrSpsUmXQ8IXqEbPyEsud7gFVHMVlXs',
    appId: '1:276682577009:android:396691a9584e52696237d0',
    messagingSenderId: '276682577009',
    projectId: 'feca-82a65',
    storageBucket: 'feca-82a65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCX-K25eO4gWf0137USquHCIyfjPpjT0k',
    appId: '1:276682577009:ios:2e0d6d7d037305396237d0',
    messagingSenderId: '276682577009',
    projectId: 'feca-82a65',
    storageBucket: 'feca-82a65.appspot.com',
    iosBundleId: 'com.example.feca',
  );
}
